extends:
  - spectral:oas

# Custom rules adjustments for Monica API OpenAPI spec
rules:
  # Keep critical errors enabled
  oas3-api-servers: error
  oas3-schema: error
  oas3-valid-schema-example: error
  oas3-unused-component: warn

  # Downgrade some strict rules to warnings for practical usage
  operation-operationId: warn
  operation-operationId-unique: error
  operation-description: warn
  operation-tags: warn
  operation-tag-defined: warn

  # Info section
  info-contact: warn
  info-description: warn
  info-license: warn

  # Path and operations
  path-params: error
  path-declarations-must-exist: error
  path-keys-no-trailing-slash: warn
  path-not-include-query: error

  # Request/Response
  oas3-valid-media-example: warn
  no-eval-in-markdown: error
  no-script-tags-in-markdown: error

  # Server URLs - allow development URLs
  oas3-server-trailing-slash: warn
